variables:                                                                      
    CONTAINER_TEST_IMAGE: new_build_$CI_COMMIT_SHA                              
                                                                                
before_script:                                                                  
                                                                                
build:
    image: docker:latest
    script:                      
        - export DOCKER_API_VERSION=1.19
        - docker build -t $CONTAINER_TEST_IMAGE --file docker/Dockerfile_GITLAB_CI .
    tags:
        - docker_roulette
