# Dockerfile for JENKINS CI
FROM ubuntu-pystorm:latest

COPY . /home/git/pystorm

# These are the commands that a developer would type to build and run
# the automated tests for PyStorm

RUN export HOME="/home/git" \
    && cd /home/git/pystorm \
    && mkdir build \
    && cd build \
    && cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..  \
    && cmake --build . --config Release

WORKDIR /home/git/pystorm/build/
