vlog -work work BDDecoder_tb.sv
vlog -work work BDIfc_tb.sv
vlog -work work BDSrcSink.sv
vlog -work work ChannelSrcSink.sv
vlog -work work FPGASerializer_tb.sv
vlog -work work OKCoreBD_tb.sv
vlog -work work PCMapper_tb.sv
vlog -work work PCParser_tb.sv
vlog -work work SpikeFilterArray_tb.sv
vlog -work work TimeMgr_tb.sv
vlog -work work BDEncoder_tb.sv
vlog -work work BDSerializer_tb.sv
vlog -work work BDTagSplit_tb.sv
vlog -work work Core_tb.sv
vlog -work work Deserializer_tb.sv
vlog -work work FPGA_TO_BD_tb.sv
vlog -work work OKCoreTestHarness_tb.sv
vlog -work work Serializer_tb.sv
vlog -work work SpikeGeneratorArray_tb.sv
vlog -work work TimeUnitPulser_tb.sv
